services:
#  mongodb:
#    image: mongo:latest
#    container_name: ascent-mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#
#  redis:
#    image: redis:latest
#    container_name: ascent-redis
#    ports:
#      - "6379:6379"

  friend-service:
    build:
      context: .
      dockerfile: service.friend/Dockerfile
    container_name: ascent-friend-service
#    depends_on:
#      - mongodb
#      - redis
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - REDIS_HOST=host.docker.internal

  proxy:
    build:
      context: .
      dockerfile: core-proxy/Dockerfile
    container_name: ascent-proxy
    ports:
      - "25565:25565"
#    depends_on:
#      - redis
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=proxy

  lobby:
    build:
      context: .
      dockerfile: core-lobby/Dockerfile
    container_name: ascent-lobby
#    depends_on:
#      - redis
#      - mongodb
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=lobby-1
      - ASCENT_ADVERTISE_HOST=lobby

  skyblock:
    build:
      context: .
      dockerfile: skyblock.hub/Dockerfile
    container_name: ascent-skyblock
#    depends_on:
#      - redis
#      - mongodb
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=skyblock-1
      - ASCENT_ADVERTISE_HOST=skyblock
      - ASCENT_SERVER_PORT=25566
      - ASCENT_SERVER_TYPE=HUB

  island:
    build:
      context: .
      dockerfile: skyblock.island/Dockerfile
    container_name: ascent-island
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=island-1
      - ASCENT_ADVERTISE_HOST=island
      - ASCENT_SERVER_PORT=25568
      - ASCENT_SERVER_TYPE=ISLAND

#volumes:
#  mongodb_data:
