services:
#  mongodb:
#    image: mongo:latest
#    container_name: ascent-mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#
#  redis:
#    image: redis:latest
#    container_name: ascent-redis
#    ports:
#      - "6379:6379"

  friend-service:
    build:
      context: .
      dockerfile: service.friend/Dockerfile
    container_name: ascent-friend-service
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - REDIS_HOST=host.docker.internal

  party-service:
    build:
      context: .
      dockerfile: service.party/Dockerfile
    container_name: ascent-party-service
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - REDIS_HOST=host.docker.internal

  proxy:
    build:
      context: .
      dockerfile: core-proxy/Dockerfile
    container_name: ascent-proxy
    ports:
      - "25565:25565"
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=proxy

  lobby:
    build:
      context: .
      dockerfile: core-lobby/Dockerfile
    container_name: ascent-lobby
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=lobby-1
      - ASCENT_ADVERTISE_HOST=lobby

  skyblock:
    build:
      context: .
      dockerfile: skyblock.hub/Dockerfile
    container_name: ascent-skyblock
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=skyblock-1
      - ASCENT_ADVERTISE_HOST=skyblock
      - ASCENT_SERVER_PORT=25566
      - ASCENT_SERVER_TYPE=HUB

  island:
    build:
      context: .
      dockerfile: skyblock.island/Dockerfile
    container_name: ascent-island
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=island-1
      - ASCENT_ADVERTISE_HOST=island
      - ASCENT_SERVER_PORT=25568
      - ASCENT_SERVER_TYPE=ISLAND

  dungeon-hub:
    build:
      context: .
      dockerfile: skyblock.dungeon_hub/Dockerfile
    container_name: ascent-dungeon-hub
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=dungeon-hub-1
      - ASCENT_ADVERTISE_HOST=dungeon-hub
      - ASCENT_SERVER_PORT=25567
      - ASCENT_SERVER_TYPE=DUNGEON_HUB

  dungeon:
    build:
      context: .
      dockerfile: skyblock.dungeon/Dockerfile
    container_name: ascent-dungeon
    environment:
      - REDIS_HOST=host.docker.internal
      - MONGODB_URI=mongodb://host.docker.internal:27017
      - ASCENT_SERVER_NAME=dungeon-1
      - ASCENT_ADVERTISE_HOST=dungeon
      - ASCENT_SERVER_PORT=25569
      - ASCENT_SERVER_TYPE=DUNGEON