rootProject.name = "ascent"
include(":commons")
include(":database")
include(":core-skyblock")
include(":core-lobby")
include(":core-proxy")
include(":loader")
include(":service.friend")
include(":service.party")
include(":skyblock.island")