bind = "0.0.0.0:25565"
online-mode = true
player-info-forwarding-mode = "modern"
forwarding-secret-file = "forwarding.secret"
bungee-plugin-message-channel = true
config-version = "2.7"
force-key-authentication = true
motd = "<gold>Ascent Network"

[servers]
lobby = "lobby:25567"
skyblock = "skyblock:25566"
try = ["lobby", "skyblock"]

[forced-hosts]

[advanced]
accepts-transfers = false
